"""Generate `docs/usage/cli-reference.md` from the Typer app's own `--help`.

Run via `uv run poe docs-cli`. `tests/test_docs_drift.py` regenerates the page
in-memory and fails if the committed file differs, so per-command options can
never drift from the code — that test is the enforcement point; this script
only writes.

Rich's boxed help renderer is disabled (`rich_markup_mode = None`) so the
captured text is plain Click help: no box-drawing characters, no ANSI, no
trailing padding. `COLUMNS` is pinned so wrapping is reproducible on any
terminal. Both are scoped to the render, because the drift test calls
`render()` inside the pytest process, where a leaked `COLUMNS` or a
permanently de-riched `app` would change what other CLI tests see.
"""

from __future__ import annotations

import sys
from pathlib import Path

from typer.main import get_group
from typer.testing import CliRunner

from introspect.cli import app

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "usage" / "cli-reference.md"

# Pinned so the generated wrapping is identical everywhere.
HELP_COLUMNS = "88"
HELP_ENV = {"COLUMNS": HELP_COLUMNS, "TERM": "dumb", "NO_COLOR": "1"}

PROG_NAME = "introspy"

HEADER = """# CLI reference

<!--
Generated by scripts/gen_cli_docs.py from `introspy --help`. Do not edit by
hand — run `uv run poe docs-cli` after changing a command or option.
-->

Every command and option, taken verbatim from the CLI's own `--help`. For what
the commands are *for*, see [CLI](cli.md).

"""


def render() -> str:
    """Render the full reference page as Markdown."""
    runner = CliRunner()

    def help_for(args: list[str]) -> str:
        result = runner.invoke(
            app, [*args, "--help"], prog_name=PROG_NAME, env=HELP_ENV
        )
        if result.exit_code != 0:  # pragma: no cover - defensive
            msg = f"`{PROG_NAME} {' '.join(args)} --help` exited {result.exit_code}"
            raise RuntimeError(msg)
        return result.output.strip("\n")

    # get_group (not get_command) so the multi-command app types as a
    # click.Group and `.commands` resolves.
    command_names = sorted(get_group(app).commands)

    previous_markup = app.rich_markup_mode
    app.rich_markup_mode = None  # plain Click help instead of Rich's panels
    try:
        parts = [HEADER, "## `introspy`\n\n```\n", help_for([]), "\n```\n"]
        for name in command_names:
            parts.append(f"\n## `introspy {name}`\n\n```\n")
            parts.append(help_for([name]))
            parts.append("\n```\n")
    finally:
        app.rich_markup_mode = previous_markup
    return "".join(parts)


def main() -> int:
    """Write the reference page."""
    OUTPUT_PATH.write_text(render())
    sys.stdout.write(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
